### ────────────────────────────────────────────────────  시공사 ────────────────────────────────────────────────────────────────────

### 권한체크
GET http://175.207.12.138:10100/api/v1/providers
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ4UklMcGJyLTZ3bktVbGlacURSb1o5R04tLTJfQ09nRnZELWpROFRMdjc0In0.eyJleHAiOjE2MjU2Mjc5NzcsImlhdCI6MTYyNTYyNzY3NywianRpIjoiMDZiNGEyNDItM2Q1ZC00ZmFhLTgwMGItMTM4ZjE0ZGQxZWVkIiwiaXNzIjoiaHR0cDovLzE3NS4yMDcuMTIuMTM4OjEwMDUwL2F1dGgvcmVhbG1zL2twcCIsInN1YiI6IjUxMzM4ZmFjLTVkMjgtNGI2Ny1hNmU5LWE1YTZkZmI3MzQwOCIsInR5cCI6IkJlYXJlciIsImF6cCI6IndlYiIsInNlc3Npb25fc3RhdGUiOiI0MTY4YTk2ZC05N2JkLTQ3NjYtYmY0MC0zNmUzYmI4ZTkzY2IiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIlBST1ZJREVSIl19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InByb3ZpZGVyMSJ9.m3qso0-yK9ENL3GXSn-Q7CuwJjcJOTgmJ0zFiftz6ZVTHo0woj-Chi3PK4qxV6ssaa42_2_R52GcN9yGSk-hgFjbcBqxQXLhe20C4O3IRrb70e34byN0dA-dlTlRXSqETVQX9uBejM09TN-A7BJ1Umd_7Fr-nylutdanLWxu5Qw4li_AyEieSJw4WZRcKtwW8WBiaX9tgDRROtEEdNSuJfTvMby3RbFsaLXQ83ZC9tDpm-leTTpdKNL6SUEjWnNIPc2sECa4fKJi3RpTiR6UV358MrgR7AU0YXSpHCgffB8JnUnUVMl9rEKVZGbhlVD3srOb9utlal28GLlOVpUvgg